### ISSUE TITLE
Shared locks?

### ISSUE THREAD

**Issue by gauteh** [yoshuawuyts/fd-lock#11]
Hi, as far as I can see this is not yet possible. It would be great with shared locks, essentially `LOCK_SH` in [`flock`](https://man7.org/linux/man-pages//man2/flock.2.html). `fs3` has [`shared_lock`](https://docs.rs/fs3/0.5.0/fs3/trait.FileExt.html#tymethod.lock_shared), but not in a `LockGuarded` out-of-scopey-unlockey way.

**Comment by yoshuawuyts** [comment]
@gauteh thanks for sharing! - I wasn't aware of `shared_lock`; that makes it seem closer to an `std::sync::RwLock` than a `std::sync::Mutex` and maybe we should change the design to accommodate that?

**Comment by yoshuawuyts** [comment]
Update: I have a working version for Windows. Going to do Unix next (:
