### ISSUE TITLE
Provide a `try_new` API for unsupported platforms

### ISSUE THREAD

**Issue by euclio** [yoshuawuyts/fd-lock#18]
Right now, if running this code on an unsupported platform it just panics. It would be nice if there was an API to check if locks were supported and handle it gracefully.

**Comment by yoshuawuyts** [comment]
Hi, thanks for opening this! There is no precedent in the stdlib for the behavior you're describing, so I'm reluctant to go that route. In the stdlib, if you call a function which is not supported on a platform (usually tier 2 or lower), that will also result in a runtime error.

I'd be open to use more restrictive cfg flags so it becomes a compile error instead. But I don't think we should expose a new API for this purpose.
