### ISSUE TITLE
Repo and release not in sync?

### ISSUE THREAD

**Issue by notmandatory** [yoshuawuyts/fd-lock#23]
Hi I noticed the latest [crates.io version](https://crates.io/crates/fd-lock/versions) for this repo is `3.0.3` but I don't see that change reflected in this repo, the latest commit to [`Cargo.toml` on the `master`](https://github.com/yoshuawuyts/fd-lock/blob/master/Cargo.toml) branch shows version `3.0.2`. Am I missing something or are you using a different repo to publish to crates.io?

**Comment by sunfishcode** [comment]
This appears to be my mistake. The only difference between the released 3.0.3 and the git repo here is the final patch which bumps the `version` field to 3.0.3, which I apparently forgot to push to the repo. I've now submitted #24 to fix this.

@yoshuawuyts What would you think of using [cargo-release](https://crates.io/crates/cargo-release) to publish releases for this repo? I use it in other projects and it works well and helps avoid such errors :-).

**Comment by notmandatory** [comment]
No prob, thanks for getting it updated!

**Comment by yoshuawuyts** [comment]
@sunfishcode oh that could be neat. It has some defaults though that I don't necessarily love (the way it automatically tags new pre-releases), but I don't think that should prevent us from adopting the tool.

Are you suggesting we run it locally, or have you integrated it with GitHub actions before?

**Comment by sunfishcode** [comment]
I'm just suggesting using it locally; I guess main change would be that it adds version tags, like `v3.0.3`.

Also, cargo-release recently changed to not tag pre-releases by default anymore :-).

**Comment by yoshuawuyts** [comment]
Ohh, yeah that works for me. I'm on board with switching to this!
