### ISSUE TITLE
Avoid panic on dropping lock

### ISSUE THREAD

**Issue by nathaniel-daniel** [yoshuawuyts/fd-lock#34]
I noticed the documentation for the locks states that the drop impl may panic if there is a problem with unlocking. Looking at unix and windows, only windows seems to panic on drop due to errors while unlocking, while the unix implementation seems to ignore errors. Is it even possible for unlocks on unix to create an error?

Regardless, I think making all platforms avoid panics and ignore errors would be better, as that mirrors Rust file behavior more closely.
At the very least, I think adding a method to allow manually unlocking and returning a result on errors would be helpful so that users who wish to do so can avoid panicking if they fail to unlock a file.

If this is a desired change, I am willing to submit a PR.

If the panic on drop behavior is intended, I think that unix should also panic on drop so that all platforms behave the same.

**Comment by sunfishcode** [comment]
That makes sense to me. I'd like to hear from @yoshuawuyts before committing to this change though, and they're out of office until December 19th.

I don't know of any situation where `flock` on any Unix platform can fail on unlock, if an `flock` has previously succeeded on the same file descriptor.

**Comment by yoshuawuyts** [comment]
Hi, yes I'd be in favor of this change!

**Comment by nathaniel-daniel** [comment]
Great thanks! I'll open a PR in the next few days when I get time. Just to be clear, I should just ensure that errors on unlocking are ignored across all platforms, and I don't need to introduce a new function to allow consuming a lock, catching errors while unlocking?
