### ISSUE TITLE
Return proper Error for `try_*` on Windows

### ISSUE THREAD

**Issue by nathaniel-daniel** [yoshuawuyts/fd-lock#35]
On Unix, using the `try_*` family of functions compares the error result to check if the error is a `WouldBlock` error, as seen [here](https://github.com/yoshuawuyts/fd-lock/blob/ad733ba603b48c7d056a237767987629c5b56b36/src/sys/unix/rw_lock.rs#L25-L34). On Windows however, any error that occurs while using the `try_*` is incorrectly reported as a `WouldBlock` error, as [the actual error is ignored](https://github.com/yoshuawuyts/fd-lock/blob/ad733ba603b48c7d056a237767987629c5b56b36/src/sys/windows/rw_lock.rs#L53-L62).

This can be seen on Windows with the following example:
```rust
use fd_lock::RwLock;
use std::fs::File;
use std::os::windows::fs::OpenOptionsExt;

fn main() {
    let file = File::options()
        .read(true)
        .write(false)
        .access_mode(0)
        .open("test.lock")
        .expect("failed to create file");
    
    let mut file = RwLock::new(file);

    let _lock = file.write().expect("failed to lock"); 
}
```

This code will panic with `failed to lock: Os { code: 5, kind: PermissionDenied, message: "Access is denied." }`, due to the `access_mode(0)` flag. However, if the code is modified to instead use `try_write`, the panic becomes `failed to lock: Kind(WouldBlock)`, hiding the actual error. 

The error returned by Windows to denote that a call to `try_*` failed seems to be [error 33, ERROR_LOCK_VIOLATION](https://learn.microsoft.com/en-us/windows/win32/debug/system-error-codes--0-499-#ERROR_LOCK_VIOLATION). Unfortunately, Rust's `std::io::Error` seems to classify this as `std::io::ErrorKind::Uncategorized`, so a match would need to be done on the error code. 

I think that the Windows implementation should perform a match on the returned error for the `try_*` functions, as that is what Unix does. Additionally, I think its important for callers to be able to differentiate between a lock already being held on a file and a lock that failed due to some I/O error.

**Comment by yoshuawuyts** [comment]
This seems reasonable to me, and probably something that should be fixed. @nathaniel-daniel would this be something you'd be interested in implementing?

**Comment by nathaniel-daniel** [comment]
Yes I am. I'll open a PR for this in the next few days when I get some time.
